# Generated by Django 5.0.4 on 2024-11-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('token', models.CharField(max_length=64)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
    ]
