# Generated by Django 5.0.4 on 2024-12-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resettoken',
            name='token',
            field=models.CharField(max_length=360),
        ),
        migrations.AlterField(
            model_name='resettoken',
            name='user_email',
            field=models.EmailField(max_length=254),
        ),
    ]
